[workspace]
authors = ["nandi <78769380+codegod100@users.noreply.github.com>"]
channels = ["conda-forge"]
name = "gasm"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
clang-17 = ">=17.0.6,<18"
redis-server = ">=7.4.0,<8"
